# Generated by Django 4.2.7 on 2023-12-17 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rent',
            name='bookinstance',
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='status',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookinstance', to='app.rent'),
        ),
    ]
