# Generated by Django 4.2.7 on 2023-12-18 08:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0003_remove_bookinstance_status_rent_bookinstance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookinstances', to='app.book'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='bookinstance',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rent', to='app.bookinstance'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='reader',
            field=models.ForeignKey(max_length=256, on_delete=django.db.models.deletion.CASCADE, related_name='rents', to='app.reader'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='user',
            field=models.ForeignKey(blank=True, max_length=256, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rents', to=settings.AUTH_USER_MODEL),
        ),
    ]
